"""empty message

Revision ID: 90963a7119db
Revises: bbfb55b54ab5
Create Date: 2023-04-28 12:28:42.006798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90963a7119db'
down_revision = 'bbfb55b54ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
